server:
  port: 8082
spring:
 application:
  name: rbpomtuci
 datasource:
  url: jdbc:postgresql://localhost:8080/postgres
  username: ${JDBC_USER}
  password: ${JDBC_PASSWORD}
 jpa:
  hibernate:
   ddl-auto: update
  show-sql: true

jwt:
 secret: VoronkinNikitaAlekseevich1BIB22009
 expiration: 3600000